/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  FirewallConsumerBase,
  FirewallConsumerBaseInterface,
} from "../FirewallConsumerBase";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_firewall",
        type: "address",
      },
      {
        internalType: "address",
        name: "_firewallAdmin",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "newAdmin",
        type: "address",
      },
    ],
    name: "FirewallAdminUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "newFirewall",
        type: "address",
      },
    ],
    name: "FirewallUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "acceptFirewallAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "firewallAdmin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "targetPayload",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "safeFunctionCall",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "bool",
        name: "status",
        type: "bool",
      },
    ],
    name: "setApprovedTarget",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_firewall",
        type: "address",
      },
    ],
    name: "setFirewall",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_firewallAdmin",
        type: "address",
      },
    ],
    name: "setFirewallAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class FirewallConsumerBase__factory {
  static readonly abi = _abi;
  static createInterface(): FirewallConsumerBaseInterface {
    return new Interface(_abi) as FirewallConsumerBaseInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): FirewallConsumerBase {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as FirewallConsumerBase;
  }
}
