/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ApprovedCallsPolicy__factory } from "./ApprovedCallsPolicy__factory";
export { FirewallConsumerBase__factory } from "./FirewallConsumerBase__factory";
